# .github/workflows/android-ci.yml
name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Necesitamos permisos de hardware para el emulador
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download dependencies
        run: ./gradlew --no-daemon dependencies

      # 1. Tests unitarios (rápidos, sin emulador)
      - name: Run unit tests
        run: ./gradlew --no-daemon test

      # 2. Configurar y levantar emulador para Espresso
      - name: Create AVD
        run: |
          sdkmanager --install "system-images;android-34;google_apis;x86_64"
          avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --device "pixel_4" --force

      - name: Start emulator
        run: |
          nohup emulator -avd test -no-snapshot -noaudio -no-window -gpu swiftshader_indirect -no-boot-anim &
          adb wait-for-device
          # a veces tarda en estar listo
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          adb shell input keyevent 82
        timeout-minutes: 5

      # 3. Tests instrumentados / Espresso
      - name: Run Android Instrumented Tests (Espresso)
        run: ./gradlew --no-daemon connectedAndroidTest

      # (opcional) publicar reportes
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: |
            **/build/reports/tests/**
            **/build/reports/androidTests/**
